# docker skapar ett nätverk
# mysql, gin är i detta fall host names inom detta nätverk
services:
  mysql:
    # hämtas från docker hub
    image: mysql:8.0.45
    # om containern crashar, starta om den
    restart: unless-stopped
    # hämtas från .env-fil
    environment:
      MYSQL_ROOT_PASSWORD: ${DBPASS}
      MYSQL_DATABASE: ${DBNAME}
    # där mysql sparar all data, vilktigt för att ha persistant data ifall containern skulle tas bort ex
    volumes:
      - db-data:/var/lib/mysql

  gin:
    image: eliassk/e-commerce:latest
    # starta mysql först (behöver ej vara redo dock)
    depends_on:
      - mysql
    environment:
      DBUSER: ${DBUSER}
      DBPASS: ${DBPASS}
      DBURL: mysql:3306 # inne i containern är hostname mysql!
      DBNAME: ${DBNAME}
    # datorn lyssnar på port 8080, skickar traffik till containern på samma port
    ports:
      - "80:8080"

volumes:
  db-data:
