services:
  mysql:
    image: mysql:8.0.45
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DBPASS}
      MYSQL_DATABASE: ${DBNAME}
    volumes:
      - db-data:/var/lib/mysql

  gin:
    build: .
    depends_on:
      - mysql
    environment:
      DBUSER: ${DBUSER}
      DBPASS: ${DBPASS}
      DBURL: mysql:3306
      DBNAME: ${DBNAME}
    ports:
      - "8080:8080"

volumes:
  db-data: